---
# Source: consul/templates/connect-inject-serviceaccount.yaml

apiVersion: v1
kind: ServiceAccount
metadata:
  name: consul-oc-consul-connect-injector-webhook-svc-account
  namespace: default
  labels:
    app: consul
    chart: consul-helm
    heritage: Tiller
    release: consul-oc
