---
# Source: consul/templates/mesh-gateway-serviceaccount.yaml

apiVersion: v1
kind: ServiceAccount
metadata:
  name: consul-oc-consul-mesh-gateway
  namespace: default
  labels:
    app: consul
    chart: consul-helm
    heritage: Tiller
    release: consul-oc
    component: mesh-gateway
