---
# Source: consul/templates/mesh-gateway-clusterrolebinding.yaml

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: consul-oc-consul-mesh-gateway
  labels:
    app: consul
    chart: consul-helm
    heritage: Tiller
    release: consul-oc
    component: mesh-gateway
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: consul-oc-consul-mesh-gateway
subjects:
  - kind: ServiceAccount
    name: consul-oc-consul-mesh-gateway
    namespace: default
