---
# Source: consul/templates/mesh-gateway-service.yaml

apiVersion: v1
kind: Service
metadata:
  name: consul-oc-consul-mesh-gateway
  namespace: default
  labels:
    app: consul
    chart: consul-helm
    heritage: Tiller
    release: consul-oc
    component: mesh-gateway
spec:
  selector:
    app: consul
    release: "consul-oc"
    component: mesh-gateway
  ports:
    - name: gateway
      port: 443
      targetPort: 443
  type: ClusterIP
