---
# Source: consul/templates/server-clusterrole.yaml

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: consul-oc-consul-server
  labels:
    app: consul
    chart: consul-helm
    heritage: Tiller
    release: consul-oc
rules:
- apiGroups: ["policy"]
  resources: ["podsecuritypolicies"]
  resourceNames:
  - consul-oc-consul-server
  verbs:
  - use
