---
# Source: consul/templates/client-clusterrole.yaml

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: consul-oc-consul-client
  labels:
    app: consul
    chart: consul-helm
    heritage: Tiller
    release: consul-oc
rules: []
