---
# Source: consul/templates/client-serviceaccount.yaml

apiVersion: v1
kind: ServiceAccount
metadata:
  name: consul-oc-consul-client
  namespace: default
  labels:
    app: consul
    chart: consul-helm
    heritage: Tiller
    release: consul-oc
