---
# Source: consul/templates/client-clusterrolebinding.yaml

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: consul-oc-consul-client
  labels:
    app: consul
    chart: consul-helm
    heritage: Tiller
    release: consul-oc
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: consul-oc-consul-client
subjects:
  - kind: ServiceAccount
    name: consul-oc-consul-client
    namespace: default
